name: flutter_shop
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.1.1
  firebase_auth: ^5.1.1
  google_sign_in: ^6.0.1
  provider: ^6.0.4
  auto_route: ^8.2.0
  flutter_bloc: ^8.0.1
  drift: ^2.4.0
  intl: ^0.19.0
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.11
  auto_route_generator: ^8.0.0
  drift_dev: ^2.1.0
