// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsN4WopOTS1rNLg4PMaazwuXAabVzmJso',
    appId: '1:1083969419659:web:bb64f7b740d62af5a8978e',
    messagingSenderId: '1083969419659',
    projectId: 'fluttershop-df9d8',
    authDomain: 'fluttershop-df9d8.firebaseapp.com',
    storageBucket: 'fluttershop-df9d8.appspot.com',
    measurementId: 'G-V1ZBNM4ZN3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuRg-FN-4lfFzcwx4H56ebT4UKTqIFstg',
    appId: '1:1083969419659:android:a5084a626211a3d0a8978e',
    messagingSenderId: '1083969419659',
    projectId: 'fluttershop-df9d8',
    storageBucket: 'fluttershop-df9d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHWE39XStxSuAhTli-b86x3mqIi9FNv4k',
    appId: '1:1083969419659:ios:2ba60084df4cad36a8978e',
    messagingSenderId: '1083969419659',
    projectId: 'fluttershop-df9d8',
    storageBucket: 'fluttershop-df9d8.appspot.com',
    iosBundleId: 'com.example.flutterShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHWE39XStxSuAhTli-b86x3mqIi9FNv4k',
    appId: '1:1083969419659:ios:2ba60084df4cad36a8978e',
    messagingSenderId: '1083969419659',
    projectId: 'fluttershop-df9d8',
    storageBucket: 'fluttershop-df9d8.appspot.com',
    iosBundleId: 'com.example.flutterShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAsN4WopOTS1rNLg4PMaazwuXAabVzmJso',
    appId: '1:1083969419659:web:84e76d6cbdaa609ca8978e',
    messagingSenderId: '1083969419659',
    projectId: 'fluttershop-df9d8',
    authDomain: 'fluttershop-df9d8.firebaseapp.com',
    storageBucket: 'fluttershop-df9d8.appspot.com',
    measurementId: 'G-7HVH2CY9KK',
  );

}